@Library('Shared') _

pipeline {
    agent{ label 'linux'}

    stages {
        
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Code') {
            steps{
                script {
                    checkout_code('https://github.com/impankaj91/wonderlust.git','main')
                }
            }
        }

        stage('Verified the Image Tag'){
            steps{
               sh "We are deploying the Version ${params.docker_image_tag}" 
            }
        }

        stage('Implement Build Tag in Manifest'){
            steps {
                script {
                   dir('kubernetes') {
                   sh "sed -i -e s/wonderlust-frontend.*/wonderlust-frontend:${params.docker_image_tag}/g frontend.yaml"
                   sh "sed -i -e s/wonderlust-backend.*/wonderlust-backend:${params.docker_image_tag}/g backend.yaml" 
                }
                }
            }
        }

    }

}