@Library('Shared') _

pipeline {
    agent{ label 'linux'}

    stages {
        stage('Hello') {
            steps {
                echo "Hello World ${params.docker_image_tag}"
            }
        }
    }

}